[package]
name = "hook-analyser"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
swc_common = "0.33.26"
swc_ecma_ast = "0.113.5"
swc_ecma_parser = "0.144.1"
swc_ecma_visit = "0.99.1"
